  import SessionContextProvider from "@/Components/SessionContextProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TeleMed24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <>
      <html lang="en">
        <body className={inter.className}>
          <SessionContextProvider>
            {children}
          </SessionContextProvider>
        </body>
      </html>
    </>
  );
}
